PUT http://localhost:5089/users/ae0c61df-b91c-40d8-9dfc-5c3892ee6d55
Content-Type: application/json

{
  "id": "ae0c61df-b91c-40d8-9dfc-5c3892ee6d55",
  "firstName": "Celine",
  "lastName": "Gabrielle",
  "email": "celinegabrielle@yahoo.com",
  "password": "hello123"
}