---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perkihub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: perkihub
    spec:
      containers:
        - name: perkihub
          image: felixarjuna/perkihub:1.0.1
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
  selector:
    matchLabels:
      app: perkihub
---
apiVersion: v1
kind: Service
metadata:
  name: perkihub
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: perkihub
