@host=http://localhost:5089

POST {{host}}/api/events
Content-Type: application/json

{
  "title": "Hello world",
  "date": "2023-02-21T20:30:00",
  "speaker": "Pdt. John Kusuma",
  "topic": "Programming"
}