GET http://localhost:5089/api/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MGEyNTE4Ny03ZjBhLTRmZDYtYjhjNi03ZThjMDFlYTA5YzAiLCJnaXZlbl9uYW1lIjoiRmVsaXgiLCJmYW1pbHlfbmFtZSI6IkFyanVuYSIsImp0aSI6IjNlYTM2ZGVhLTBkNjMtNGI5Zi04MzBlLTBiYjQwNGU1MTQ5MCIsImV4cCI6MTY3OTczNTY4OCwiaXNzIjoiUGVya2lIdWIiLCJhdWQiOiJQZXJraUh1YiJ9.0VkeNwY7A7SeH7xzU257oYsauQrniM8FKCttd4Z0Xzs